"""add subscription billing period

Revision ID: 2b80db066b3d
Revises: bc0465a05645
Create Date: 2026-08-06 13:32:33.644104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b80db066b3d'
down_revision: Union[str, Sequence[str], None] = 'bc0465a05645'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        'subscriptions',
        sa.Column(
            'current_period_start',
            sa.DateTime(),
            nullable=True
        )
    )

    op.add_column(
        'subscriptions',
        sa.Column(
            'current_period_end',
            sa.DateTime(),
            nullable=True
        )
    )

    # Backfill existing subscriptions.
    # Existing subscriptions use their subscribed_at as the
    # beginning of the current billing period.
    op.execute("""
        UPDATE subscriptions
        SET
            current_period_start = subscribed_at,
            current_period_end = subscribed_at + INTERVAL '30 days'
    """)

    # Make the columns mandatory after existing rows are populated.
    op.alter_column(
        'subscriptions',
        'current_period_start',
        nullable=False
    )

    op.alter_column(
        'subscriptions',
        'current_period_end',
        nullable=False
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'current_period_end')
    op.drop_column('subscriptions', 'current_period_start')
    # ### end Alembic commands ###
